title: "解説系AITuberを作ろう！"
summary: "プログラミングの知識が不要な「解説系AITuberの作り方」について紹介しています。1.ChatGPTで作った台本からAI音声を作成します。2.オリジナル3Dキャラクターを作成します。3.3Dキャラクターの口の動きと音声を合わせて録画します。4.テロップを入れてYoutube用の動画を作成します。"
topics: ["生成ai", "aituber", "youtube"] # トピック（5つまで）
published: false # falseだと下書き
price: 0 # 有料の場合200〜5000
chapters:
  - introduction
  - chatgptconcept
  - chatgptscript
  - 3dvrm
  - tts
  - 3dsoftware
  - obs
  - movie
  - postface
