title: "解説系AITuberを作ろう！"
summary: "こんにちは！「解説系AITuberを作ろう」を読んでいただきありがとうございます。\nこの本では、プログラミングの知識が不要な「解説系AITuberの作り方」について紹介していきます。\n\n📕この本の概要📕\nChatGPTで作った台本からAI音声を作成します。\n\nオリジナル3Dキャラクターを作成します。\n3Dキャラクターの口の動きと音声を合わせて録画します。\nテロップを入れてYoutube用の動画を作成します。\n\n💻推奨環境\n\nWindows 10 以上\nゲーミング用途に使えるようなGPU性能のあるPC\n\nこの本で作成できる解説系AITuberのイメージは以下の通りです。\n私自身、作り始めたばかりで、これから解説系AITuberを始めていこうと思っています。\n\nhttps://www.youtube.com/watch?v=Z9F20UBlIeA\n解説系AITuberに興味を持ってもらえたら、\nこの本の内容はみなさんにとって楽しいものになるかと思います！\nぜひ最後まで読んで実践してみてくださいね。\n\nこの本で分かること\n\n解説系AITuberを作るための必要な知識のみ介していきます。\n\nChatGPTを使ったチャンネル紹介の作り方\nChatGPTを使った台本の作り方\n3Dキャラを作成するためのソフトの紹介\n3Dキャラを動かすためのソフトの紹介\n音声合成AIソフトの紹介\n録画用ソフトの紹介\nAI字幕がつく動画編集ソフトの紹介"
topics: ["ChatGPT","生成ai", "aituber", "youtube"] # トピック（5つまで）
published: false # falseだと下書き
price: 0 # 有料の場合200〜5000
chapters:
  - introduction
  - chatgptconcept
  - chatgptscript
  - 3dvrm
  - tts
  - 3dsoftware
  - obs
  - movie
  - postface
  - contribute
